
// Generated by build tool, do not edit
using System;
using System.Reflection;
[assembly: AssemblyCopyright("Copyright © 2021-2022 Topten Software. All Rights Reserved")]
[assembly: AssemblyVersion("0.1.106")]
[assembly: AssemblyFileVersion("0.1.106")]
[assembly: AssemblyCompany("Topten Software")]
[assembly: AssemblyProduct("TranslateKit")]

static class BuildInfo
{
	public static DateTime Date = new DateTime(2022, 10, 6, 1, 14, 24, DateTimeKind.Utc);
}
	