
// Generated by build tool, do not edit
using System;
using System.Reflection;
[assembly: AssemblyCopyright("Copyright © 2021 Topten Software. All Rights Reserved")]
[assembly: AssemblyVersion("0.1.101")]
[assembly: AssemblyFileVersion("0.1.101")]
[assembly: AssemblyCompany("Topten Software")]
[assembly: AssemblyProduct("TranslateKit")]

static class BuildInfo
{
	public static DateTime Date = new DateTime(2021, 8, 10, 11, 38, 7, DateTimeKind.Utc);
}
	